from __future__ import annotations
import uuid
from datetime import datetime
from sqlalchemy import String, DateTime, ForeignKey, Text, Integer, JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base

class Report(Base):
    __tablename__ = "reports"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4, index=True)
    analysis_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("analyses.id", ondelete="CASCADE"), nullable=False, index=True, unique=True)
    
    # Quantitative scores generated by AI (0-100)
    score_quality: Mapped[int] = mapped_column(Integer, default=100, nullable=False)
    score_security: Mapped[int] = mapped_column(Integer, default=100, nullable=False)
    score_performance: Mapped[int] = mapped_column(Integer, default=100, nullable=False)
    score_maintainability: Mapped[int] = mapped_column(Integer, default=100, nullable=False)
    
    # Detailed findings JSON structure containing specific code smells, bugs, recommendations
    findings: Mapped[dict] = mapped_column(JSON, default=list, nullable=False)
    
    # Full Markdown report contents
    markdown_content: Mapped[str] = mapped_column(Text, nullable=False)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationships
    analysis: Mapped["Analysis"] = relationship(back_populates="report")
